### PR TITLE
add back pop-os animation frames

### LINKED ISSUE #30: What happened to the pop-logo theme?
Has the pop-logo theme now completely been removed? 
The version installed from ISO stopped working after the latest update (falling back to ubuntu-text, horribly). Once the package is removed with ```sudo apt remove plymouth-theme-pop-logo``` there is no candidate to reinstall it.

Has it now been complete removed?

Thank you.

### PR DESCRIPTION
**Pull request by TermoZour**
This PR should fix #30 . I have tested it on my local machine using Pop!_OS 22.04 LTS with Wayland, GNOME 42.5 and it seems to work. 

I get the loading animation but my system boots too fast to show the entire thing.
Acording to [this issue from plymouth](https://gitlab.freedesktop.org/plymouth/plymouth/-/issues/110), the purpose of plymouth is to show "something" while the system is still booting, not to slow down the booting process so you can see the animation, so this may not be relevant for newer machines, but I still found something I could improve and gave it a shot.

For faster systems I will be trying to make a BGRT-based theme [referenced here section 3.4](https://wiki.archlinux.org/title/plymouth) so it will show the OEM logo and a spinner, then dump us right to the login manager, similar to how Windows does it.

### CODE REVIEW

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
I see no issues caused by this on a purely functional level. I have tested on Intel, AMD, and NVIDIA hardware. So far the problem I'm seeing is in regards to aesthetics. On encrypted systems the progress bar is directly over the decryption text.

Example:

[plymouth-new.webm](https://user-images.githubusercontent.com/11048214/205730665-77cccaa8-2841-4c78-8b3b-651ceda20423.webm)

**Comment by TermoZour** [comment]
Right, I did not test that one as I'm using unencrypted partitions. I will look into it. Most likely I only need to set text alignment so it's not centered by default.

**Comment by TermoZour** [comment]
@n3m0-22 can you change `TitleVerticalAlignment=.382` to `TitleVerticalAlignment=.5` in `pop-basic.plymouth` and test to see if it fixes the issue? On my system it seems to not affect anything. I'm also running it on a 13 inch 1440p screen so maybe that is why? Either increase `TitleVerticalAlignment` or `DialogVerticalAlignment` with ".2".

I couldn't find any sort of reference docs for plymouth. That specific text might not be classified as "Dialog" nor "Title" so I would need to hunt for a different setting. I'm also working on another plymouth theme and all changes have been made through trial and error...

**Comment by n3m0-22** [comment]
After a bit of experimentation it looks like the simplest way to make this work is changing `DialogVerticalAlignment` from `DialogVerticalAlignment=.5` to `DialogVerticalAlignment=.47`. This keeps the decryption prompt very close to the center while providing enough space for the progress bar to not overlap the text. I have tested this with HD, 2K, 3K, and 4K resolutions as well as multi-display setups without issue.

Example:

plymouth-progress


Note:

It happens so fast I could not get a screenshot, but if you look very closely you can see a dot `progress-01.png` (this is the beginning of the progress bar) for just a moment below the decryption prompt when it first shows on the screen. I don't believe it is very noticeable unless you are looking for it but it should be noted.

**Review by n3m0-22 — DISMISSED** [review]

**Comment by TermoZour** [comment]
Right, moving the text actually higher rathen than lower is a fix, but in theory, after the loading is done, the entire Pop!_OS logo should appear. It doesn't in my case as the system boots too fast as is. I also may need to change the name of the "reveal" animation so it's actually registered. 
Again, as I have no reference documentation for what plymouth variables I can change or how the files should be named, I don't know.

I will modify the text so it sits under the progress bar. So a `.7` instead of `.5` should be enough.

**Comment by n3m0-22** [comment]
The changes you have made work. I see why you want the text below so there will be room for the logo. Perhaps taking a look at this file will be of help.

https://github.com/pop-os/plymouth/blob/0493e8428c5e7dccb02daa8382bfcd85f77b29a9/src/plugins/splash/two-step/plugin.c

**Review by 13r0ck — CHANGES_REQUESTED** [review]
It was an intentional decision to remove the animation from the pop!_os theme.

1) So this cannot be a modification to the pop-basic theme. It needs to be a separate plymouth theme that the user could switch to. 
2) Currently Pop!_OS uses a fork of plymouth that beaks many themes that arn't our default `pop-basic` theme. So this will also require changes to the plymouth code itself to fix that bug

**Comment by TermoZour** [comment]
Well, in that case I have another approach if you're interested. Why stare at a gray screen when you can look at the firmware logo and have the Pop!_OS spinner showing up instead?
https://user-images.githubusercontent.com/16005294/206154935-749cbe34-aa9f-45cb-af4e-bc0fbdd78375.mp4

This one is also based on the pop-basic theme.

Depending on the system it can look slick or not. But I find it much better to see Pop specific loading icon and my firmware logo rather than stare at a grey screen for 2-3 seconds.

**Comment by n3m0-22** [comment]
I see no issue with that, but as stated above it will need to be a separate option. It will then need to be tested again to make sure it is working with the Pop!_OS fork of plymouth.

**Comment by mmstick** [comment]
The reason for the gray screen is to match the GDM login screen. It's to make it possible to have a flicker-free boot. You'll immediately know the system is loading when you get to the gray screen and then GDM appears with the same background color.

**Comment by TermoZour** [comment]
I thought the flicker I experienced was because the OS would somehow detect the 2 monitors and apply settings on boot. I unplugged my external monitor and left the laptop to boot.

Apparently the process is as follows: OEM logo, black screen, plymouth starts with OEM logo again and my Pop!_OS spinner. In the case of the default plymouth theme, it goes like this: OEM logo, black screen, GDM background color. then when GDM is ready, it just pops up.

So if I can make the OEM logo fade in when plymouth starts, and then have the screen fade to GDM background color, there would be absolutely no flickering.

**Comment by n3m0-22** [comment]
If you can do that I will test it, but it will still need approval. It should also still not be the default. If after there is a working tested version that can be considered, but I think that would be outside the purview of this PR.

**Comment by TermoZour** [comment]
I'll see what I can come up with for the other themes. 
In terms of this specific PR, I will need to make the pop-basic theme with logo a separate one in this same repo. Then see what happens from there.

**Comment by AdityaGarg8** [comment]
> Well, in that case I have another approach if you're interested. Why stare at a gray screen when you can look at the firmware logo and have the Pop!_OS spinner showing up instead? https://user-images.githubusercontent.com/16005294/206154935-749cbe34-aa9f-45cb-af4e-bc0fbdd78375.mp4
> 
> This one is also based on the pop-basic theme.
> 
> Depending on the system it can look slick or not. But I find it much better to see Pop specific loading icon and my firmware logo rather than stare at a grey screen for 2-3 seconds.

This one looks so good! Where can I get it from?

**Comment by TermoZour** [comment]
@AdityaGarg8 here: https://github.com/TermoZour/pop-spinner-theme

**Comment by AdityaGarg8** [comment]
> @AdityaGarg8 here: https://github.com/TermoZour/pop-spinner-theme

Thanks!

**Comment by TermoZour** [comment]
I could only find [this](https://github.com/freedesktop/plymouth/tree/master/themes/fade-in) related to any sort of fading transition for plymouth, but the lack of documentation doesn't help me much. Right now I have no time to work on this and the scope of this PR is long gone anyway. If I find anything and come up with better alternatives, I'll open another PR.

For now, I will be closing this and will make all custom themes available from my profile for whoever wants to try and tweak any of them. Thank you all for the feedback!

**Pull request closed without merging**
