### PR TITLE
Add new basic Pop theme

### PR DESCRIPTION
**Pull request by mmstick**
Provides a simple theme which focuses primarily on the decryption screen.

- Features a blinking cursor within the password entry
- Places the password prompt text beneath the entry, centered.
- Entry has a return key to signal for the user to press enter

screenshot from 2018-06-05 13-32-33

### CODE REVIEW

**Comment by jackpot51** [comment]
This looks really good. I am testing it on my NVIDIA laptop

**Comment by mmstick** [comment]
Just added the return key arrow to the entry, and it should be ready now.

**Review by jackpot51 — APPROVED** [review]

**Comment by brs17** [comment]
@mmstick @jackpot51 

img_20180515_093229

No Pop!_OS logo on the wilp14 on intel graphics

**Comment by jackpot51** [comment]
We removed the Pop logo, for simplicity

**Comment by brs17** [comment]
ah, ok.

**Comment by aden-young** [comment]
This looks really slick! Will it be rolled out automatically? My computer still has no theme during the boot / decryption process.

**Comment by mmstick** [comment]
@aden-young This has been shipping since the PR was merged. You should be seeing it (I've been seeing it on all the systems I've installed Pop on).

**Pull request merged**
