### PR TITLE
Pop upgrade integration

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by leviport — CHANGES_REQUESTED** [review]
When running a `pop-upgrade release upgrade systemd` the Pop! logo flash briefly on the screen, then disappear for the remainder of the upgrade. The text showed up and looked good, but the Pop! logo was gone.

**Comment by mmstick** [comment]
Indeed. The new plymouth commit hasn't been built yet

**Comment by brs17** [comment]
Oftentimes the message on the plymouth screen runs too long and off of the screen (horizontally).
IMG_20190917_103838

On systems with older graphics cards, the Pop!_OS logo is cut off as well.
IMG_20190916_133031

**Comment by mmstick** [comment]
I could reduce the information displayed. Perhaps keep it to `Unpacking $package`.

**Comment by brs17** [comment]
Potentially reading the size of the display and fitting the content within that could be a solution. Or more conservatively, centering everything in a practically guaranteed rectangle (1024x768?).

Although reducing the text to just `Upgrading $package` would definitely solve the horizontal overflow issue.

**Comment by brs17** [comment]
Upon completion of the upgrade, the boot menu in the BIOS should be updated to say Pop!_OS 19.04.

This is what it looks like on laptops with a dualboot.
IMG_20190917_114136

**Comment by mmstick** [comment]
The upgrade script calls this before rebooting, which should be setting it based on the `PRETTY_NAME`:

```sh
    if test -d '/sys/firmware/efi/'; then
        current_bootnum=$(efibootmgr | grep BootCurrent | awk -F' ' '{print $2}')
        new_label=$(cat /etc/os-release | grep PRETTY | awk -F'"' '{print $2}')
        efibootmgr -b "${current_bootnum}" -B
        efibootmgr -c -L "${new_label}"
    fi
```

**Comment by leviport** [comment]
The plymouth screen is weirdly sized on the troublesome monitor in the lab:

IMG_20190918_093218

That image also shows something else we noticed, the "Unpacking Unpacking" text. We also saw "processing triggers for for" in this image: 

IMG_20190918_093118

**Comment by mmstick** [comment]
The messages are fixed in the most recent commits of `pop-upgrade`. The placement may be that the system is reporting a higher screen resolution than what's actually being displayed. I could move the logo closer to the text.

**Comment by leviport** [comment]
It looks like this branch is only in Bionic. Eventually we'll also be needing it in Disco, so would it make sense to add it sooner rather than later?

**Comment by mmstick** [comment]
This will be merged into disco once it is merged into bionic. That way I don't have to update two separate branches at the same time.

**Comment by brs17** [comment]
I don't think it is a blocking regression but on the disk decryption page, the cursor does not disapear when pressing <kbd>Enter</kbd>

blinking_cursor

**Review by jackpot51 — DISMISSED** [review]

**Comment by leviport** [comment]
After a (forced) upgrade to 19.10 from 19.04 on serw11, I got some dependency issues with Nvidia packages that prevented me from installing updates with `sudo apt upgrade`. The resulting output is attached.

[1904-to-1910-error.txt](https://github.com/pop-os/plymouth-theme/files/3691553/1904-to-1910-error.txt)

**Review by leviport — APPROVED** [review]

**Comment by jackpot51** [comment]
So, I think this added in the Pop!_OS logo on unencrypted installs which we had not had before. Not sure that is desired.

**Comment by mmstick** [comment]
The only time the logo's opacity is set to 1 is when the `system-updates` message is received, so it shouldn't appear except for when a release upgrade is being performed.

**Review by jackpot51 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
I ran a few more installs & upgrades and did not see the plymouth splash return before login screen. We'll keep an eye out for it, but for now I couldn't reproduce it.

**Pull request merged**
