### PR TITLE
fix: center plymouth when display resolutions !=

### PR DESCRIPTION
**Pull request by 13r0ck**
The current scaling can be a bit strange with this PR. I might make a PR after this one that should fix plymouth scaling with multiple monitors of differing resolutions if we decide its necessary

### CODE REVIEW

**Comment by 13r0ck** [comment]
using the apt script might not install this correctly, I'm not sure.

Install manually by copying `/usr/share/plymouth/themes/pop-basic/pop-basic.script` from this repo to the same location on system. Then run `sudo update-initramfs -u` and the change should be made.

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Is this not building because of the underscore in the branch name?

**Comment by jackpot51** [comment]
Yes, it needs to be a dash

**Comment by 13r0ck** [comment]
closed by #25

**Pull request closed without merging**
